version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "python"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
